name: grocery_express
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

# Application versioning
version: 1.0.0+1

# Dart SDK version compatibility
environment:
  sdk: '>=2.19.0 <4.0.0'

# Dependencies for your app
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  provider: ^6.0.5
  image_picker: ^0.8.7+3
  permission_handler: ^11.3.1
  http: ^1.2.2
  get: ^4.6.6
  fluttertoast: ^8.2.10
  shared_preferences: ^2.3.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/broccoli.jpg
    # - assets/tomato.jpg
    - assets/default_profile.png
    - assets/drinks.png
    - assets/biscuits.png
    - assets/meats.png
    - assets/fruits.png
    - assets/vegetables.png

    
